# Configuration for CV
person:
  first_name: James
  last_name: Doss-Gollin
  title: Assistant Professor
  university: Rice University
  department: Department of Civil and Environmental Engineering
  department_link: https://cee.rice.edu/
  email: jdossgollin@rice.edu
  web: https://dossgollin-lab.github.io/
  github: jdossgollin
  googlescholar: 6ifLBBsAAAAJ
  orcid: 0000-0002-3428-2224
  subject: "adaptive and resilient infrastructure"
  address:
    line1: 6100 Main Street, Ryon Lab 204-MS 318
    postcode: Houston, TX, 77005
    country: USA

paths:
  bib_path: my-papers
  yaml_path: data

publications:
  - title: Papers
    file: my-papers.bib

sections:
  - title: Research Interests
    file: interests.yml
  - title: Appointments
    file: appointments.yml
  - title: Education
    file: education.yml
  - title: Invited Talks
    file: talks.yml
  - title: Workshop Presentations
    file: workshops.yml
  - title: Grants and Contracts
    file: grants.yml
  - title: Teaching
    file: teaching.yml
  - title: Advising
    file: advising.yml
  - title: Awards
    file: awards.yml
  - title: Media Coverage
    file: media.yml
  - title: Peer Review
    file: peerreview.yml
  - title: Professional Experience
    file: experience.yml
  - title: Workshops and Sessions Organized
    file: convene.yml
